// PM2 Ecosystem Configuration
// This file allows you to manage all services from a single configuration

module.exports = {
  apps: [
    {
      name: 'user-service',
      script: '/opt/ecommerce/ecommerce-microservices/services/user-service/src/server.js',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      error_file: '/var/log/ecommerce/user-service-error.log',
      out_file: '/var/log/ecommerce/user-service.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'product-service',
      script: '/opt/ecommerce/ecommerce-microservices/services/product-service/src/server.js',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
      },
      error_file: '/var/log/ecommerce/product-service-error.log',
      out_file: '/var/log/ecommerce/product-service.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'order-service',
      script: '/opt/ecommerce/ecommerce-microservices/services/order-service/src/server.js',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
        PORT: 3003,
      },
      error_file: '/var/log/ecommerce/order-service-error.log',
      out_file: '/var/log/ecommerce/order-service.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'payment-service',
      script: '/opt/ecommerce/ecommerce-microservices/services/payment-service/src/server.js',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
        PORT: 3004,
      },
      error_file: '/var/log/ecommerce/payment-service-error.log',
      out_file: '/var/log/ecommerce/payment-service.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'notification-service',
      script: '/opt/ecommerce/ecommerce-microservices/services/notification-service/src/server.js',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
        PORT: 3005,
      },
      error_file: '/var/log/ecommerce/notification-service-error.log',
      out_file: '/var/log/ecommerce/notification-service.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'api-gateway',
      script: '/opt/ecommerce/ecommerce-microservices/api-gateway/src/server.js',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PORT: 8080,
      },
      error_file: '/var/log/ecommerce/api-gateway-error.log',
      out_file: '/var/log/ecommerce/api-gateway.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'frontend',
      script: 'serve',
      args: '-s /opt/ecommerce/frontend/build -l 3000',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '200M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/var/log/ecommerce/frontend-error.log',
      out_file: '/var/log/ecommerce/frontend.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
    },
  ],
};
